### ISSUE TITLE
[OnGoing] Development on windows

### ISSUE THREAD

**Issue by Nasicus** [ArkEcosystem/mobile-wallet#18]
With this issue I'd like to make a thread where we can discuss how you can develop the ark-mobile wallet on Windows (if you're not a windows dev and don't have anything to contribute, don't post here, especially stuff like "why don't you switch to Mac/Linux" posts are not required!) .

I had and still have, several problems, so I'd like to give other windows-devs help on what I did to get it running in a "basic" version. My hope is that together we can fix all problems and then (if required and if it's not all my own fault) add it to the readme or create a wiki page or something similar.
I will always update this post with new findings and inputs from other guys in other posts (if there will be any that is ;) ).

So here we go with my "insights".

----

# Versions:
```
node --version
v8.9.3

npm --v
5.6.0

git --version
git version 2.15.1.windows.2

# See comment below!
cordova --v
7.1.0

ionic --v
3.19.0
```

# How to make it work (even though there ARE errors during some commands)

```
npm install

# If you have errors, just try  the next steps, it might still work
ionic cordova prepare

# call npm install again (fixes arkjs  problem)
npm install

# deploy it to android (if you deploy it like this you DON'T have to deploy it again, because later you can just run npm run ionic:serve and your mobile phone will just update/download the app directly from your computer, obviously you have to be in the same network)

ionic cordova run android --live-reload

#browser
npm run ionic:serve
```

# Problem: Cordova version (Cannot find module) => solved
First I installed cordova (as written in the readme) via `npm install -g cordova`.
However this installed `8.0.0` for me. When I later ran `ionic cordova prepare` I got a lot of error messages like this:

```Failed to restore plugin "cordova-plugin-x-socialsharing" from config.xml. You might need to try adding it again. Error: Error: Cannot find module '../cordova/platform_metadata'```

After some time I finally decided to downgrade cordova to `7.1.0`:  `npm install -g cordova@7.1.0`.
For me  the messages above are now gone.

Can anyone confirm this?

# Problem: Cordova-custom-config: git submodule => not solved
The second problem, which still occurs for me during `ionic cordova prepare`, is the following:
```
Failed to restore plugin "cordova-custom-config" from config.xml. You might need to try adding it again. Error: Failed to fetch plugin cordova-custom-config@^5.0.1 via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! code 128
npm ERR! Command failed: C:\Git\cmd\git.EXE submodule update -q --init --recursive
npm ERR! fatal: 'submodule' appears to be a git command, but we were not
npm ERR! able to execute it. Maybe git-submodule is broken?
npm ERR!
```
I did not yet find a solution for this and already tried various things.

Note that I can still run ark-mobile (at least in browser) despite of this problem. However it would be nice if this could be fixed!

# Problem: arkjs not found => not solved (workaround)

When I run the app via: `npm run ionic:serve`  I got the following error in the browser:

```
Error: Cannot find module "arkjs"
    at webpackMissingModule (http://localhost:8100/build/main.js:1553:86)
    at new ArkApiProvider (http://localhost:8100/build/main.js:1553:168)
    at _createClass (http://localhost:8100/build/vendor.js:10211:26)
    at _createProviderInstance$1 (http://localhost:8100/build/vendor.js:10169:26)
    at resolveNgModuleDep (http://localhost:8100/build/vendor.js:10154:17)
    at NgModuleRef_.get (http://localhost:8100/build/vendor.js:11246:16)
    at resolveDep (http://localhost:8100/build/vendor.js:11749:45)
    at createClass (http://localhost:8100/build/vendor.js:11613:32)
    at createDirectiveInstance (http://localhost:8100/build/vendor.js:11433:37)
    at createViewNodes (http://localhost:8100/build/vendor.js:12874:49)
```
In the code in `ArkApiProvider`  `require('arkjs') ` is called.
However in my `node_modules` folder there's simply no `arkjs` folder anymore. That's also the reason why it cannot be found.

I then noticed that `package.json` and `packagelock.json` is modified after `ionic cordova prepare` was executed. I reverted the changes in the package files and run `npm install` again. Now `npm run ionic:serve` appears to work.

However it remains to find out: Why is the `package-lock.json` and the `package.json` modified? When does it occur? How can we prevent it?

# Platforms

## Browser
Appears to be working

## Android
Apperas to be woring

## IOS
Untested

-------------------

Any input of other windows devs on this would be appreciated.

Maybe everything works for you? If so what node and npm version do you have? Do you have any idea how to fix it?

**Comment by alexbarnsley** [comment]
I don't actually run prepare. Try these steps:

```
npm install
ionic cordova build android
```

You may also need the below, but try without first:
```
npm install -g cordova-android
```

Let me know what steps work, as we may need to update the readme. Then again it could just be a Windows issue

**Comment by luciorubeens** [comment]
```
$ ionic info

cli packages: (/usr/local/lib/node_modules)
    @ionic/cli-utils  : 1.19.0
    ionic (Ionic CLI) : 3.19.0

global packages:
    cordova (Cordova CLI) : 7.0.1

local packages:
    @ionic/app-scripts : 3.1.2
    Cordova Platforms  : android 6.4.0 browser 4.1.0 ios 4.5.4
    Ionic Framework    : ionic-angular 3.9.2

System:
    ios-deploy : 1.9.2
    Node       : v8.4.0
    npm        : 5.4.2
    OS         : macOS High Sierra
    Xcode      : Xcode 9.2 Build version 9C40b

Environment Variables:
    ANDROID_HOME : not set

Misc:
    backend : pro
```

**Comment by Nasicus** [comment]
@alexbarnsley 

interesting. Unfortunately I still get the same  `Cordova-custom-config` exception when I do `ionic cordova build android`.

**Comment by luciorubeens** [comment]
@Nasicus Try reinstalling manually:

`ionic cordova plugin rm cordova-custom-config`
`ionic cordova plugin add cordova-custom-config`

**Comment by Nasicus** [comment]
This gives me the same error :/

I now also tried downgrading ionic to the same version as you have (@luciorubeens ) and also downgrading npm (because I read something somewhere).

Now I have a different error :trollface: 

```
Error: cmd: Command failed with exit code 1 Error output:
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-9a0b67c9 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-92a6e60b\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: Cloning into 'C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-92a6e60b\5ccd600b0b7fd3ae204edc9e69c1c30406d07747'...
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-9a0b67c9 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-92a6e60b\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-9a0b67c9 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-92a6e60b\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: fatal: unable to fork
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-9a0b67c9 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-92a6e60b\5ccd600b0b7fd3ae204edc9e69c1c30406d07747:
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-xiangpingmeng-plist-js-git-7b94e505 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-2122f40d\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: Cloning into 'C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-2122f40d\5ccd600b0b7fd3ae204edc9e69c1c30406d07747'...
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-xiangpingmeng-plist-js-git-7b94e505 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-2122f40d\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: error: cannot spawn sh: No such file or directory
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-xiangpingmeng-plist-js-git-7b94e505 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-2122f40d\5ccd600b0b7fd3ae204edc9e69c1c30406d07747: fatal: unable to fork
npm ERR! git clone C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-xiangpingmeng-plist-js-git-7b94e505 C:\Users\Patrick\AppData\Local\Temp\npm-216-59146822\git-cache-2122f40d\5ccd600b0b7fd3ae204edc9e69c1c30406d07747:
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit  xiangpingmeng/plist.js resetting remote C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376 because of error: { Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:275:12)
npm WARN addRemoteGit     at emitTwo (events.js:126:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:214:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:925:16)
npm WARN addRemoteGit     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:xiangpingmeng/plist.js.git C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376: Cloning into bare repository 'C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376'...
npm ERR! git clone --template=C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:xiangpingmeng/plist.js.git C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376: error: cannot spawn ssh: No such file or directory
npm ERR! git clone --template=C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:xiangpingmeng/plist.js.git C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376: fatal: unable to fork
npm ERR! code 128
npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git@github.com:xiangpingmeng/plist.js.git C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376
npm ERR! Cloning into bare repository 'C:\Users\Patrick\AppData\Roaming\npm-cache\_git-remotes\git-github-com-xiangpingmeng-plist-js-git-cbe72376'...
npm ERR! error: cannot spawn ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Patrick\AppData\Roaming\npm-cache\_logs\2017-12-30T12_14_17_451Z-debug.log
```

Anyway I'll try some more stuff myself and come back here if I find anything useful.

**Comment by Nasicus** [comment]
So I couldn't get the errors away.
But it appears it matters not, since the app is working; both on my real android phone and in the browser.
I personally will also not invest any more time into this.
But I'd like still to tell you how my "setup" is, if anyone has problems: Please see my edit in the first post for this.

And I must say I find it **very** cool that you only have to deploy the app to your android once, and after that you can simply run `npm run ionic:serve` and the device  will download the current version of the app automatically...this makes testing directly on the device so much easier!
